name: Validate and Push web static files to Development

on:
  push:
    branches:
      - '**'   

  pull_request:
    branches:
      - develop

jobs:
    validate:
      runs-on: robot-shop-runner-azure-dev

    push:
      runs-on: robot-shop-runner-azure-dev