name: Validate and Push web static files to Development

on:
  push:
    branches-ignore:
      - main  

  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  deploy:
    uses: robot-shop-DevOps/robot-shop-github-actions/.github/workflows/static-sites.yaml@main
    with:
      WORKING_DIR: ./web
      UPLOAD_DIR: ./web/static
    secrets: inherit