name: Validate and Push web static files to Development

on:
  push:
    branches-ignore:
      - main  

  pull_request:
    branches:
      - develop

  workflow_dispatch:

env:
  AZURE_STORAGE_ACCOUNT: "robotshopdevweb"
  AZURE_STORAGE_CONTAINER: "static"

jobs:
    validate:
      runs-on: robot-shop-runner-azure-dev
      steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install linters
        run: |
          npm install -g eslint
          npm install -g stylelint stylelint-config-standard
          npm install -g htmlhint

      - name: Lint HTML files
        working-directory: web/
        run: |
          htmlhint ./**/*.html

      - name: Lint CSS files
        working-directory: web/
        run: |
          stylelint ./**/*.css --config .stylelintrc.json

      - name: Lint JavaScript files
        working-directory: web/
        run: |
          eslint ./**/*.js --quiet


    push:
      if: ${{ github.ref_name == 'develop' }}
      needs: validate
      runs-on: robot-shop-runner-azure-dev
      steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure CLI
        run: |
          az login --service-principal \
          --username ${{ secrets.ROBOT_SHOP_DEV_AZURE_CLIENT_ID_AZURE_STORAGE }} \
          --password ${{ secrets.ROBOT_SHOP_DEV_AZURE_CLIENT_SECRET_AZURE_STORAGE }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.ROBOT_SHOP_DEV_AZURE_SUBSCRIPTION_ID }}

      - name: Push Static Files to Azure Storage
        run: |
          az storage blob upload-batch \
          --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} \
          --destination ${{ env.AZURE_STORAGE_CONTAINER }} \
          --source web \
          --overwrite 